"use client";
import Link from "next/link";
import { useActionState } from "react";
import { GOAL_STATUS } from "@/lib/constants";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import type { ObjectiveActionResult } from "./actions";
export type GoalDefaults={title:string;description:string;metric:string;unit:string;targetValue:string;currentValue:string;status:string;ownerId:string;startDate:string;dueDate:string};
export const EMPTY_GOAL:GoalDefaults={title:"",description:"",metric:"",unit:"unidades",targetValue:"",currentValue:"0",status:"PLANNING",ownerId:"",startDate:"",dueDate:""};
export function GoalForm({action,users,defaults=EMPTY_GOAL,editing=false}:{action:(p:ObjectiveActionResult|null,d:FormData)=>Promise<ObjectiveActionResult>;users:{id:string;fullName:string}[];defaults?:GoalDefaults;editing?:boolean}){const[state,formAction,pending]=useActionState(action,null);const e=state?.fieldErrors??{};return <form action={formAction} className="space-y-6">{state?.message&&!state.ok&&<p className="rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{state.message}</p>}<Card><CardHeader><CardTitle>Informações da meta</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="Título" htmlFor="title" required error={e.title}><Input id="title" name="title" defaultValue={defaults.title} required/></Field><Field className="sm:col-span-2" label="Descrição" htmlFor="description" error={e.description}><Textarea id="description" name="description" defaultValue={defaults.description}/></Field><Field label="Indicador" htmlFor="metric" required error={e.metric}><Input id="metric" name="metric" defaultValue={defaults.metric} placeholder="Ex.: Novos clientes" required/></Field><Field label="Unidade" htmlFor="unit" required error={e.unit}><Input id="unit" name="unit" defaultValue={defaults.unit} required/></Field><Field label="Valor alvo" htmlFor="targetValue" required error={e.targetValue}><Input id="targetValue" name="targetValue" defaultValue={defaults.targetValue} inputMode="decimal" required/></Field><Field label="Valor atual" htmlFor="currentValue" required error={e.currentValue}><Input id="currentValue" name="currentValue" defaultValue={defaults.currentValue} inputMode="decimal" required/></Field><Field label="Status" htmlFor="status" error={e.status}><Select id="status" name="status" defaultValue={defaults.status}>{Object.entries(GOAL_STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Responsável" htmlFor="ownerId" error={e.ownerId}><Select id="ownerId" name="ownerId" defaultValue={defaults.ownerId}><option value="">Sem responsável</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName}</option>)}</Select></Field><Field label="Início" htmlFor="startDate" error={e.startDate}><Input id="startDate" name="startDate" type="date" defaultValue={defaults.startDate}/></Field><Field label="Prazo" htmlFor="dueDate" error={e.dueDate}><Input id="dueDate" name="dueDate" type="date" defaultValue={defaults.dueDate}/></Field></CardContent></Card><div className="flex justify-end gap-2"><Link href="/metas" className={buttonVariants({variant:"secondary"})}>Cancelar</Link><Button type="submit" loading={pending}>{editing?"Salvar meta":"Criar meta"}</Button></div></form>}
