import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth/current-user";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PRIORITIES, TASK_STATUS } from "@/lib/constants";
import { formatDate, formatDateTime } from "@/lib/format";

export default async function TaskDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  await requireUser();
  const { id } = await params;
  const task = await db.task.findFirst({ where: { id, archivedAt: null }, include: { project: true, client: true, responsible: true, creator: true, assignees: { include: { user: true } }, checklistItems: { orderBy: { position: "asc" } }, comments: { where: { deletedAt: null }, orderBy: { createdAt: "desc" }, include: { author: true } }, deadlineRequests: { orderBy: { createdAt: "desc" } } } });
  if (!task) notFound();
  return <><PageHeader title={task.title} description={`${TASK_STATUS[task.status as keyof typeof TASK_STATUS] ?? task.status} · ${PRIORITIES[task.priority as keyof typeof PRIORITIES] ?? task.priority}`} /><div className="grid gap-4 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><CardTitle>Detalhes</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{task.description ?? "Sem descrição."}</p><p><span className="text-muted">Projeto:</span> {task.project?.name ?? "—"}</p><p><span className="text-muted">Cliente:</span> {task.client?.tradeName ?? task.client?.legalName ?? "—"}</p><p><span className="text-muted">Prazo:</span> {formatDate(task.dueDate)}</p><p><span className="text-muted">Responsável:</span> {task.responsible?.fullName ?? "Não definido"}</p><p><span className="text-muted">Participantes:</span> {task.assignees.map((a) => a.user.fullName).join(", ") || "—"}</p></CardContent></Card><Card><CardHeader><CardTitle>Checklist</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{task.checklistItems.length ? task.checklistItems.map((item) => <p key={item.id}>{item.doneAt ? "✓" : "○"} {item.content}</p>) : <p className="text-muted">Nenhum item.</p>}</CardContent></Card></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Comentários</CardTitle></CardHeader><CardContent className="space-y-3">{task.comments.length ? task.comments.map((comment) => <div key={comment.id} className="border-b border-border pb-3 text-sm"><p>{comment.content}</p><p className="mt-1 text-xs text-muted">{comment.author.fullName} · {formatDateTime(comment.createdAt)}</p></div>) : <p className="text-sm text-muted">Nenhum comentário.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Solicitações de prazo</CardTitle></CardHeader><CardContent className="space-y-3">{task.deadlineRequests.length ? task.deadlineRequests.map((request) => <div key={request.id} className="border-b border-border pb-3 text-sm"><p>{request.reason}</p><p className="mt-1 text-xs text-muted">{request.status} · novo prazo {formatDate(request.requestedDeadline)}</p></div>) : <p className="text-sm text-muted">Nenhuma solicitação.</p>}</CardContent></Card></div></>;
}
